interface RegionList {
	[key: string]: {
		regions: string[];
	};
}

interface CountryList {
	code: string;
	name: string;
}

export const countryList: CountryList[] = [
	{ code: "BO", name: "Bolivia" },
	{ code: "AR", name: "Argentina" },
	{ code: "BR", name: "Brazil" },
	{ code: "PY", name: "Paraguay" },
	{ code: "PE", name: "Peru" },
	{ code: "CO", name: "Colombia" },
	{ code: "MX", name: "Mexico" },
];

export const regionList: RegionList = {
	BO: {
		regions: [
			"Cochabamba",
			"El Alto",
			"La Paz",
			"Oruro",
			"Santa Cruz",
			"Sucre",
			"Tarija",
			"Trinidad",
		],
	},
	AR: {
		regions: [
			"Avellaneda",
			"Bahía Blanca",
			"Bariloche",
			"Belén De Escobar",
			"Buenos Aires",
			"Caleta Olivia",
			"Capital Federal",
			"Comodoro Rivadavia",
			"Córdoba",
			"Corrientes",
			"Jujuy",
			"Lanús",
			"La Plata",
			"Lomas De Zamora",
			"Mar Del Plata",
			"Mendoza",
			"Merlo",
			"Moreno",
			"Morón",
			"Neuquén",
			"Oberá",
			"Paraná",
			"Pilar",
			"Posadas",
			"Puerto Madryn",
			"Quilmes",
			"Ramos Mejía",
			"Resistencia",
			"Río Cuarto",
			"Río Gallegos",
			"Rosario",
			"Salta",
			"San Fernando",
			"San Justo",
			"San Luis",
			"San Martín",
			"San Juan",
			"San Miguel",
			"Santa Rosa",
			"Santa Fe",
			"Santiago Del Estero",
			"Temperley",
			"Tigre",
			"Trelew",
			"Tucumán",
			"Ushuaia",
		],
	},
	BR: {
		regions: [
			"Alvorada",
			"Ananindeua",
			"Anápolis",
			"Angra dos Reis",
			"Aparecida de Goiânia",
			"Aracaju",
			"Arapiraca",
			"Araraquara",
			"Araruama",
			"Armação dos Búzios",
			"Arraial do Cabo",
			"Balneário Camboriú",
			"Barueri",
			"Bauru",
			"Belém",
			"Belo Horizonte",
			"Betim",
			"São José dos Campos",
			"São José dos Pinhais",
			"São Luís",
			"São Paulo",
			"São Pedro da Aldeia",
			"São Vicente",
			"Saquarema",
			"Serra",
			"Sete Lagoas",
			"Sinop",
			"Sobral",
			"Sorocaba",
			"Sorriso",
			"Taubaté",
			"Teresina",
			"Três Lagoas",
			"Tubarão",
			"Uberaba",
			"Uberlândia",
			"Valparaíso de Goiás",
			"Várzea Grande",
			"Vila Velha",
			"Vitória",
			"Vitória da Conquista",
			"Volta Redonda",
		],
	},
	PY: { regions: ["Alto Paraná", "Asunción", "Central"] },
	PE: {
		regions: [
			"Arequipa",
			"Ayacucho",
			"Cajamarca",
			"Callao",
			"Chiclayo",
			"Chimbote",
			"Chincha Alta",
			"Cusco",
			"Huacho",
			"Huancayo",
			"Huánuco",
			"Huaraz",
			"Ica",
			"Iquitos",
			"Juliaca",
			"Lambayeque",
			"Lima Metropolitana",
			"Piura",
			"Pucallpa",
			"Puno",
			"Tacna",
			"Tarapoto",
			"Trujillo",
		],
	},
	CO: {
		regions: [
			"Arauca",
			"Armenia",
			"Barranquilla",
			"Bogotá",
			"Bucaramanga",
			"Buenaventura",
			"Cali",
			"Cartagena",
			"Cúcuta",
			"Florencia",
			"Ibagué",
			"Manizales",
			"Medellín",
			"Montería",
			"Neiva",
			"Pasto",
			"Pereira",
			"Popayán",
			"Puerto Asís",
			"Quibdó",
			"Riohacha",
			"San Andrés",
			"San José Del Guaviare",
			"Santa Marta",
			"Sincelejo",
			"Soacha",
			"Soledad",
			"Tunja",
			"Valledupar",
			"Villavicencio",
			"Yopal",
		],
	},
	MX: {
		regions: [
			"Acapulco",
			"Aguascalientes",
			"Campeche",
			"Cancún",
			"Chetumal",
			"Chihuahua",
			"Ciudad de México",
			"Ciudad Juárez",
			"Colima",
			"Cuernavaca",
			"Culiacán",
			"Durango",
			"Guadalajara",
			"Guanajuato",
			"Hermosillo",
			"La Paz",
			"Mérida",
			"Mexicali",
			"Monterrey",
			"Morelia",
			"Oaxaca",
			"Pachuca de Soto",
			"Puebla de Zaragoza",
			"Puerto Vallarta",
			"Reynosa",
			"Saltillo",
			"San Luis Potosí",
			"Santiago de Querétaro",
			"Tepic",
			"Tijuana",
			"Tlaxcala",
			"Toluca de Lerdo",
			"Tuxtla Gutiérrez",
			"Veracruz",
			"Villahermosa",
			"Xalapa-Enríquez",
			"Zacatecas",
			"Zapopan",
		],
	},
};
